name: ✨ Feature Request
description: Suggest a new feature or enhancement for Questie-Epoch
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches you’ve considered
