name: Bug Report
description: Report a reproducible bug in Questie-Epoch
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Addon Version
      description: What version of Questie-Epoch are you running?
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List exact steps so we can reproduce this bug
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Logs, screenshots, etc.
