blank_issues_enabled: false
contact_links:
  - name: 💬 Project Epoch Discord
    url: https://discord.gg/projectepoch
    about: For general support, questions, or discussions - join our Discord community!
